blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog_index'),
    path('<int:blog_id>', views.detail, name='blog_detail'),
    path('category/<int:category_id>', views.category, name='blog_category'),
    path('tag/<int:tag_id>', views.tag, name='blog_tag'),
    path('search', views.search, name='blog_search'),
]

pyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('blog.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='博客分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = "博客分类"


class Tag(models.Model):
    name = models.CharField(max_length=128, verbose_name='标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '内容标签'
        verbose_name_plural = '内容标签'


class Entry(models.Model):
    title = models.CharField(max_length=256, verbose_name='条目标题')
    author = models.ForeignKey(User, verbose_name='条目作者', on_delete=models.CASCADE, )
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='条目添加日期')
    modified_time = models.DateTimeField(auto_now=True, verbose_name='条目修改时间')
    abstract = models.TextField(max_length=256, verbose_name='内容摘要', blank=True, null=True)
    body = models.TextField(verbose_name='条目正文')
    img = models.ImageField(upload_to='blog-images', null=True, blank=True, verbose_name='条目配图')
    visited = models.PositiveIntegerField(default=0, verbose_name='条目访问量')
    category = models.ManyToManyField('Category', verbose_name='条目类别')
    tag = models.ManyToManyField('Tag', verbose_name='条目标签')

    def __str__(self):
        return self.title

    def increate_visited(self):
        self.visited += 1
        self.save(update_fields=['visited'])

    class Meta:
        ordering = ['-created_time']
        verbose_name = '条目'
        verbose_name_plural = '条目'

blog/views.py
from django.shortcuts import render
from . import models
import markdown
import pygments
from django.db.models.query import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def make_paginator(objects, page, num=2):
    paginator = Paginator(objects, num)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list, paginator


def pagination_data(paginator, page):
    """
    用于自定义展示分页页码的方法
    :param paginator: Paginator类的对象
    :param page: 当前请求的页码
    :return: 一个包含所有页码和符号的字典
    """
    if paginator.num_pages == 1:
        # 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
        return {}
    # 当前页左边连续的页码号，初始值为空
    left = []

    # 当前页右边连续的页码号，初始值为空
    right = []

    # 标示第 1 页页码后是否需要显示省略号
    left_has_more = False

    # 标示最后一页页码前是否需要显示省略号
    right_has_more = False

    # 标示是否需要显示第 1 页的页码号。
    # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
    # 其它情况下第一页的页码是始终需要显示的。
    # 初始值为 False
    first = False

    # 标示是否需要显示最后一页的页码号。
    # 需要此指示变量的理由和上面相同。
    last = False

    # 获得用户当前请求的页码号
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1

    # 获得分页后的总页数
    total_pages = paginator.num_pages

    # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
    page_range = paginator.page_range

    if page_number == 1:
        # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
        # 此时只要获取当前页右边的连续页码号，
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
        # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        right = page_range[page_number:page_number + 4]

        # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
        # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
        if right[-1] < total_pages - 1:
            right_has_more = True

        # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
        # 所以需要显示最后一页的页码号，通过 last 来指示
        if right[-1] < total_pages:
            last = True

    elif page_number == total_pages:
        # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
        # 此时只要获取当前页左边的连续页码号。
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
        # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

        # 如果最左边的页码号比第 2 页页码号还大，
        # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
        if left[0] > 2:
            left_has_more = True

        # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
        # 所以需要显示第一页的页码号，通过 first 来指示
        if left[0] > 1:
            first = True
    else:
        # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
        # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 2]

        # 是否需要显示最后一页和最后一页前的省略号
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True

        # 是否需要显示第 1 页和第 1 页后的省略号
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True

    data = {
        'left': left,
        'right': right,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'first': first,
        'last': last,
    }
    return data


# Create your views here.
def index(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)

    return render(request, 'blog/index.html', locals())


def detail(request, blog_id):
    entry = models.Entry.objects.get(id=blog_id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        'markdown_checklist.extension',
    ])
    entry.body = md.convert(entry.body)
    entry.toc = md.toc
    entry.increate_visited()
    return render(request, 'blog/detail.html', locals())


def category(request, category_id):
    c = models.Category.objects.get(id=category_id)
    entries = models.Entry.objects.filter(category=c)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)

    return render(request, 'blog/index.html', locals())


def tag(request, tag_id):
    t = models.Tag.objects.get(id=tag_id)
    entries = models.Entry.objects.filter(tag=t)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)

    return render(request, 'blog/index.html', locals())


def search(request):
    keyword = request.GET.get('keyword', default=None)
    if keyword is not None:
        entries = models.Entry.objects.filter(Q(title__icontains=keyword) |
                                              Q(body__icontains=keyword) |
                                              Q(abstract__icontains=keyword))
        page = request.GET.get('page', 1)
        entry_list, paginator = make_paginator(entries, page)
        page_data = pagination_data(paginator, page)
    else:
        error_massage = '请输入关键词'

    return render(request, 'blog/index.html', locals())

blog/templates/blog/base.html
{% load staticfiles %}
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}页面标题{% endblock %}</title>
    <!-- Bootstrap 核心CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    {#    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">#}
    <link rel="stylesheet" href="{% static 'blog/css/blog_style.css' %}">
    {% block css %}{% endblock %}


</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:blog_index' %}">Home <span class="sr-only">(current)
                    </span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'blog:blog_search' %}" method="get">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
{% endblock %}
{% block main %}
    <main role="main" class="container">

        <div class="starter-template">
            <h1>Bootstrap starter template</h1>
            <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text
                and a mostly barebones HTML document.</p>
        </div>

    </main><!-- /.container -->
{% endblock %}
{% block footer %}

    <footer class="bd-footer text-muted">
        <div class="container-fluid p-3 p-md-5">
            <ul class="bd-footer-links">
                <li><a href="https://github.com/twbs/bootstrap">关于我们</a></li>
                <li><a href="https://twitter.com/getbootstrap">联系我们</a></li>
                <li><a href="/docs/4.3/examples/">案例介绍</a></li>
                <li><a href="/docs/4.3/about/overview/">About</a></li>
            </ul>
            <p>Designed and built with all the love in the world by the <a href="/docs/4.3/about/team/">Bootstrap
                team</a> with the help of <a href="https://github.com/twbs/bootstrap/graphs/contributors">our
                contributors</a>.</p>
            <p>Currently v4.3.1. Code licensed <a href="https://github.com/twbs/bootstrap/blob/master/LICENSE"
                                                  target="_blank" rel="license noopener">MIT</a>, docs <a
                    href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="license noopener">CC BY
                3.0</a>.</p>
        </div>
    </footer>
{% endblock %}
<!-- Bootstrap 核心 JavaScript -->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}{{ entry.title }}--博客正文页面{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
{% endblock %}
{% block main %}
    <div class="main container">
        <div class="row">
            <div class="col-sm-9">
                <h1>{{ entry.title }}</h1>
                <p>
                    <span>作者：{{ entry.author }}</span>
                    <span>发布于：{{ entry.created_time }}</span>
                    <span>访问量：{{ entry.visited }}</span>
                    <span>分类：
                        {% for category in entry.category.all %}
                            <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                        {% endfor %}
                    </span>
                    <span>标签：
                        {% for tag in entry.tag.all %}
                            <a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
                        {% endfor %}
                    </span>
                </p>
                {% if entry.img %}
                    <div><img src="{{ entry.img.url }}" alt="博客配图" class="blog-img"></div>
                {% endif %}
                <div>{{ entry.toc|safe }}</div>
                <div>{{ entry.body|safe }}</div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}博客首页{% endblock %}
{% block main %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-sm-9">
                <div class="blog-lists">
                    {% for entry in entry_list %}
                        <h2><a href="{% url 'blog:blog_detail' entry.id %}">{{ entry.title }}</a></h2>
                        <p>
                            <span>作者：{{ entry.author }}</span>
                            <span>发表于：{{ entry.created_time }}</span>
                            <span>访问量：{{ entry.visited }}</span>
                        </p>
                        {% if entry.img %}
                            <div><img src="{{ entry.img.url }}" alt="博客配图" class="blog-img"></div>
                        {% endif %}
                        {% if entry.abstract %}
                            <p>{{ entry.abstract }}</p>
                        {% else %}
                            <p>{{ entry.body|truncatechars:60 }}...</p>
                        {% endif %}

                    {% endfor %}
                </div>
                {#分页#}
                <div id="paginator" class="pull-right">
                    <ul class="pagination">
                        {% if entry_list.has_previous %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ entry_list.previous_page_number }}"><i
                                    class="fa fa-chevron-left"></i>前一页</a></li>
                        {% endif %}

                        {% if first %}
                            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                        {% endif %}

                        {% if left %}
                            {% if left_has_more %}
                                <span>...</span>
                            {% endif %}

                            {% for i in left %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}


                        <li class="page-item active"><a class="page-link" href="?page={{ entry_list.number }}"
                        >{{ entry_list.number }}</a></li>

                        {% if right %}
                            {% for i in right %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}

                            {% if right_has_more %}
                                <span>...</span>
                            {% endif %}
                        {% endif %}

                        {% if last %}
                            <li class="page-item"><a class="page-link" href="?page={{ entry_list.num_pages }}"
                            >{{ entry_list.num_pages }}</a></li>
                        {% endif %}

                        {% if entry_list.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ entry_list.next_page_number }}">下一页<i
                                    class="fa fa-chevron-right"></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </main>
{% endblock %}